import{FilesetResolver,PoseLandmarker}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm";
const $=id=>document.getElementById(id),video=$("camera"),canvas=$("overlay"),ctx=canvas.getContext("2d"),start=$("startButton"),capture=$("captureButton"),switchBtn=$("switchButton"),guideBtn=$("guideButton"),permission=$("permissionScreen"),ai=$("aiStatus"),people=$("peopleStatus"),banner=$("successBanner"),bannerTitle=$("successTitle"),bannerSub=$("successSub"),countdown=$("countdown"),poseName=$("poseName"),poseHint=$("poseHint"),poseIcon=$("poseIcon"),progressCircle=$("progressCircle"),progressText=$("progressText"),resultDialog=$("resultDialog"),resultImage=$("resultImage"),metricsDialog=$("metricsDialog"),metricGrid=$("metricGrid"),poseMetrics=$("poseMetrics"),toast=$("toast");
const model="https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task",wasm="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm";
const P={heart:{n:"손하트",i:"♡",h:"두 손을 머리 위에서 모아 하트를 만들어보세요.",ms:600,t:"하트가 피어났어요!",s:"캐릭터 주변에 하트가 터집니다"},jump:{n:"점프",i:"↟",h:"전신이 보이게 선 뒤, 살짝 앉았다가 점프하세요.",ms:80,t:"날아올랐어요!",s:"날개와 별빛이 펼쳐집니다"},mimic:{n:"캐릭터 따라 하기",i:"☆",h:"양팔과 두 다리를 넓게 펴 별 모양을 만들어보세요.",ms:600,t:"싱크로율 100%!",s:"애니메이션 오라가 활성화됩니다"},highfive:{n:"하이파이브",i:"✋",h:"두 사람이 화면에 들어와 손을 높이 맞대보세요.",ms:380,t:"팀워크 폭발!",s:"하이파이브 임팩트가 시작됩니다"},family:{n:"가족·단체 포즈",i:"♧",h:"두 명 이상이 함께 들어와 모두 한 손을 높이 들어주세요.",ms:700,t:"우리 모두 주인공!",s:"캐릭터와 축하 파티가 열립니다"}};
const C=[[11,13],[13,15],[12,14],[14,16],[11,12],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];
let landmarker,stream,running=false,front=true,guide=true,mode="heart",poses=[],lastTime=-1,lastInfer=0,holdAt=0,cool=0,effect=null,shotBlob=null,baseHip=null,crouchAt=0,prevHip=null;
const key="aniroadPoseStats",fresh=()=>({sessions:0,starts:0,success:0,captures:0,shares:0,downloads:0,byPose:Object.fromEntries(Object.keys(P).map(k=>[k,0])),events:[]});
let stats=(()=>{try{return{...fresh(),...JSON.parse(localStorage.getItem(key)||"{}")}}catch{return fresh()}})();stats.sessions++;save("session");
function save(type,data={}){if(type){stats.events.push({time:new Date().toISOString(),type,pose:mode,...data});if(stats.events.length>500)stats.events.shift()}localStorage.setItem(key,JSON.stringify(stats))}
function note(msg){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)}
function status(text,state=""){ai.className=`status-pill ${state}`;ai.innerHTML=`<i></i>${text}`}
function visible(p,min=.42){return!!p&&(p.visibility??1)>=min&&(p.presence??1)>=min}
function dist(a,b){return a&&b?Math.hypot(a.x-b.x,a.y-b.y):99}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function angle(a,b,c){const x1=a.x-b.x,y1=a.y-b.y,x2=c.x-b.x,y2=c.y-b.y,d=Math.hypot(x1,y1)*Math.hypot(x2,y2);return d?Math.acos(Math.max(-1,Math.min(1,(x1*x2+y1*y2)/d)))*180/Math.PI:0}
function area(p){const q=p.filter(x=>visible(x));if(!q.length)return 0;const xs=q.map(x=>x.x),ys=q.map(x=>x.y);return(Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys))}
function mainPose(){return[...poses].sort((a,b)=>area(b)-area(a))[0]}
function setProgress(v){v=Math.max(0,Math.min(1,v));progressCircle.style.strokeDashoffset=113.1*(1-v);progressText.textContent=`${Math.round(v*100)}%`}
function select(k,user=true){mode=k;holdAt=0;baseHip=prevHip=null;crouchAt=0;document.querySelectorAll(".pose-tab").forEach(b=>b.classList.toggle("active",b.dataset.pose===k));poseName.textContent=P[k].n;poseHint.textContent=P[k].h;poseIcon.textContent=P[k].i;setProgress(0);if(user)save("pose_selected")}
document.querySelectorAll(".pose-tab").forEach(b=>b.onclick=()=>select(b.dataset.pose));
async function initAI(){status("AI 모델 불러오는 중","loading");const files=await FilesetResolver.forVisionTasks(wasm);const options=d=>({baseOptions:{modelAssetPath:model,delegate:d},runningMode:"VIDEO",numPoses:4,minPoseDetectionConfidence:.5,minPosePresenceConfidence:.5,minTrackingConfidence:.45});try{landmarker=await PoseLandmarker.createFromOptions(files,options("GPU"))}catch{landmarker=await PoseLandmarker.createFromOptions(files,options("CPU"))}status("AI 포즈 인식 준비 완료")}
async function startCamera(){stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:front?"user":"environment"},width:{ideal:960},height:{ideal:720},frameRate:{ideal:24,max:30}}});video.srcObject=stream;await new Promise(r=>video.onloadedmetadata=r);await video.play();resize();video.classList.toggle("mirrored",front);canvas.classList.toggle("mirrored",front)}
async function begin(){start.disabled=true;start.textContent="준비 중…";try{await Promise.all([initAI(),startCamera()]);permission.classList.add("dismissed");[capture,switchBtn,guideBtn].forEach(b=>b.disabled=false);running=true;stats.starts++;save("camera_started");requestAnimationFrame(loop)}catch(e){status("시작 오류","error");note(e.name==="NotAllowedError"?"카메라 권한을 허용해주세요.":"실행하지 못했습니다. 네트워크를 확인해주세요.");start.disabled=false;start.textContent="다시 시도하기"}}
function resize(){canvas.width=video.videoWidth||720;canvas.height=video.videoHeight||960}
function heart(p){if(!p)return 0;const[n,ls,rs,le,re,lw,rw]=[p[0],p[11],p[12],p[13],p[14],p[15],p[16]];if(![n,ls,rs,le,re,lw,rw].every(visible))return 0;const sw=dist(ls,rs),close=1-Math.min(1,dist(lw,rw)/Math.max(.12,sw*1.15)),high=Math.max(0,Math.min(1,(n.y+.12-(lw.y+rw.y)/2)/.18)),out=Math.max(0,Math.min(1,(dist(le,re)-dist(lw,rw))/Math.max(.08,sw)));return close*.43+high*.38+out*.19}
function mimic(p){if(!p)return 0;const[ls,rs,le,re,lw,rw,lh,rh,la,ra]=[p[11],p[12],p[13],p[14],p[15],p[16],p[23],p[24],p[27],p[28]];if(![ls,rs,le,re,lw,rw,lh,rh,la,ra].every(visible))return 0;return Math.min(1,(Math.min(angle(ls,le,lw),angle(rs,re,rw))/180)*.32+Math.min(1,dist(lw,rw)/(dist(ls,rs)*2.6))*.32+(1-Math.min(1,Math.abs(lw.y-ls.y)+Math.abs(rw.y-rs.y)))*.18+Math.min(1,dist(la,ra)/(dist(lh,rh)*2.2))*.18)}
function jump(p,now){if(!p)return 0;const[lh,rh,lk,rk,la,ra]=[p[23],p[24],p[25],p[26],p[27],p[28]];if(![lh,rh,lk,rk,la,ra].every(x=>visible(x,.35)))return 0;const hip=(lh.y+rh.y)/2,knee=(angle(lh,lk,la)+angle(rh,rk,ra))/2;if(baseHip==null)baseHip=hip;const velocity=prevHip==null?0:prevHip-hip;prevHip=hip;if(knee<145&&hip>baseHip+.008)crouchAt=now;const hit=now-crouchAt<1700&&baseHip-hip>.035&&velocity>.003;if(knee>=145&&!hit&&Math.abs(hip-baseHip)<.06)baseHip=baseHip*.985+hip*.015;return hit?1:knee<145?.55:Math.max(0,Math.min(.45,(baseHip-hip)/.07))}
function contact(){if(poses.length<2)return null;let best;for(let i=0;i<poses.length;i++)for(let j=i+1;j<poses.length;j++)for(const a of[poses[i][15],poses[i][16]])for(const b of[poses[j][15],poses[j][16]])if(visible(a)&&visible(b)){const d=dist(a,b);if(!best||d<best.d)best={d,p:mid(a,b)}}return best}
function highfive(){const c=contact();return c?Math.max(0,Math.min(1,1-c.d/.13)):0}
function family(){if(poses.length<2)return 0;const valid=poses.filter(p=>visible(p[11],.35)&&visible(p[12],.35));if(valid.length<2)return 0;const raised=valid.filter(p=>{const y=(p[11].y+p[12].y)/2;return visible(p[15])&&p[15].y<y||visible(p[16])&&p[16].y<y}).length;return Math.min(1,.35*Math.min(1,valid.length/3)+.65*raised/valid.length)}
function score(now){const p=mainPose();return mode==="heart"?heart(p):mode==="jump"?jump(p,now):mode==="mimic"?mimic(p):mode==="highfive"?highfive():family()}
function recognize(v,now){if(now<cool){setProgress(0);return}const th=mode==="jump"?.92:.72;if(v>=th){if(!holdAt)holdAt=now;const x=Math.min(1,(now-holdAt)/P[mode].ms);setProgress(x);if(x>=1){success();holdAt=0;setProgress(0)}}else{holdAt=0;setProgress(Math.max(0,(v-.25)/(th-.25))*.5)}}
function success(){cool=performance.now()+3500;effect={type:mode,start:performance.now()};stats.success++;stats.byPose[mode]=(stats.byPose[mode]||0)+1;save("pose_success",{people:poses.length});bannerTitle.textContent=P[mode].t;bannerSub.textContent=P[mode].s;banner.classList.add("show");setTimeout(()=>banner.classList.remove("show"),2400);if(mode==="jump")setTimeout(()=>photo(true),120);else{let n=2;countdown.textContent=n;const t=setInterval(()=>{n--;if(n)countdown.textContent=n;else{clearInterval(t);countdown.textContent="";photo(true)}},650)}}
function loop(now){if(!running)return;resize();if(landmarker&&video.readyState>1&&video.currentTime!==lastTime&&now-lastInfer>55){lastTime=video.currentTime;lastInfer=now;try{poses=(landmarker.detectForVideo(video,now).landmarks||[]).filter(p=>area(p)>.01);people.textContent=`${poses.length}명 감지`;recognize(score(now),now)}catch(e){console.warn(e)}}draw(now);requestAnimationFrame(loop)}
function pt(p){return{x:p.x*canvas.width,y:p.y*canvas.height}}
function draw(now){ctx.clearRect(0,0,canvas.width,canvas.height);if(guide)for(const p of poses){ctx.save();ctx.strokeStyle="rgba(255,218,145,.75)";ctx.lineWidth=Math.max(2,canvas.width/380);ctx.shadowColor="#9467ff";ctx.shadowBlur=10;for(const[a,b]of C)if(visible(p[a])&&visible(p[b])){const x=pt(p[a]),y=pt(p[b]);ctx.beginPath();ctx.moveTo(x.x,x.y);ctx.lineTo(y.x,y.y);ctx.stroke()}ctx.restore()}if(effect&&now-effect.start<2900)fx(effect.type,now-effect.start);else effect=null}
function fx(type,t){ctx.save();const fade=t<2200?1:Math.max(0,1-(t-2200)/700);ctx.globalAlpha=fade;const w=canvas.width,h=canvas.height,c=contact(),cx=c?c.p.x*w:w/2,cy=c?c.p.y*h:h*.38;ctx.textAlign="center";ctx.textBaseline="middle";if(type==="heart"){ctx.font=`${Math.max(42,w*.09)}px serif`;for(let i=0;i<14;i++){const a=i/14*Math.PI*2+t/900,r=w*(.16+.03*Math.sin(t/150+i));ctx.fillStyle=i%2?"#ff7fb4":"#ffd991";ctx.fillText("♥",w/2+Math.cos(a)*r,h*.34+Math.sin(a)*r*.72)}}else if(type==="jump"){ctx.font=`${Math.max(30,w*.055)}px sans-serif`;for(let i=0;i<22;i++){ctx.fillStyle=i%2?"#ffd991":"#fff";ctx.fillText("✦",(i*83+t*.07)%w,h-((i*71+t*.16)%h))}}else if(type==="mimic"){ctx.strokeStyle="#c2a8ff";ctx.lineWidth=6;ctx.setLineDash([18,14]);ctx.lineDashOffset=-t/18;ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*(.27+Math.sin(t/140)*.02),0,Math.PI*2);ctx.stroke()}else if(type==="highfive"){ctx.strokeStyle="#ffd991";ctx.lineWidth=8;const r=Math.min(w,h)*Math.min(.25,.04+t/4500);ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();for(let i=0;i<14;i++){const a=i/14*Math.PI*2;ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*r*.6,cy+Math.sin(a)*r*.6);ctx.lineTo(cx+Math.cos(a)*r*1.5,cy+Math.sin(a)*r*1.5);ctx.stroke()}}else{ctx.font=`${Math.max(24,w*.045)}px sans-serif`;for(let i=0;i<35;i++){ctx.fillStyle=["#ffd991","#9467ff","#7ff4d5"][i%3];ctx.fillText(i%2?"◆":"✦",(i*97)%w,(i*61+t*.08)%h)}}ctx.restore()}
async function photo(auto=false){if(!video.videoWidth)return;const p=document.createElement("canvas"),x=p.getContext("2d"),w=video.videoWidth,h=video.videoHeight;p.width=w;p.height=h;if(front){x.translate(w,0);x.scale(-1,1)}x.drawImage(video,0,0,w,h);x.drawImage(canvas,0,0,w,h);x.setTransform(1,0,0,1,0,0);const bh=Math.max(72,h*.09),g=x.createLinearGradient(0,h-bh,w,h);g.addColorStop(0,"rgba(25,14,39,.96)");g.addColorStop(1,"rgba(92,50,170,.94)");x.fillStyle=g;x.fillRect(0,h-bh,w,bh);x.fillStyle="#ffd991";x.font=`800 ${Math.max(18,w*.028)}px system-ui`;x.fillText("순천 애니로드 · AI 포즈 포토존",w*.035,h-bh*.55);x.fillStyle="#fff";x.font=`600 ${Math.max(12,w*.018)}px system-ui`;x.fillText(`${P[mode].n} · ${new Date().toLocaleDateString("ko-KR")}`,w*.035,h-bh*.22);shotBlob=await new Promise(r=>p.toBlob(r,"image/jpeg",.92));resultImage.src=URL.createObjectURL(shotBlob);stats.captures++;save("photo",{auto});resultDialog.showModal()}
function download(){if(!shotBlob)return;const u=URL.createObjectURL(shotBlob),a=document.createElement("a");a.href=u;a.download=`aniroad-${Date.now()}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);stats.downloads++;save("download")}
async function share(){if(!shotBlob)return;const f=new File([shotBlob],`aniroad-${Date.now()}.jpg`,{type:"image/jpeg"});try{if(navigator.share&&navigator.canShare?.({files:[f]})){await navigator.share({title:"순천 애니로드 AI 포즈 포토존",text:"순천 애니로드에서 오늘의 포즈를 완성했어요!",files:[f]});stats.shares++;save("share")}else download()}catch(e){if(e.name!=="AbortError")note("사진 저장을 이용해주세요.")}}
function metrics(){const rate=stats.starts?Math.round(stats.captures/stats.starts*100):0;metricGrid.innerHTML=[[stats.sessions,"접속 세션"],[stats.success,"포즈 성공"],[stats.captures,"사진 생성"],[rate+"%","촬영 전환율"],[stats.shares,"공유"],[stats.downloads,"저장"]].map(v=>`<div class="metric"><strong>${v[0]}</strong><span>${v[1]}</span></div>`).join("");const m=Math.max(1,...Object.values(stats.byPose));poseMetrics.innerHTML=Object.entries(P).map(([k,v])=>`<div class="pose-row"><span>${v.n}</span><div class="pose-bar"><i style="width:${(stats.byPose[k]||0)/m*100}%"></i></div><strong>${stats.byPose[k]||0}</strong></div>`).join("")}
function csv(){const rows=[["time","type","pose","people"],...stats.events.map(e=>[e.time,e.type,e.pose,e.people??""])],blob=new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`aniroad-poc-${Date.now()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
start.onclick=begin;capture.onclick=()=>photo(false);switchBtn.onclick=async()=>{front=!front;switchBtn.disabled=true;try{await startCamera();save("camera_switch")}catch{front=!front;note("카메라 전환에 실패했습니다.")}switchBtn.disabled=false};guideBtn.onclick=()=>{guide=!guide;guideBtn.classList.toggle("active",guide);$("guideFrame").classList.toggle("hidden-guide",!guide)};$("closeResult").onclick=()=>resultDialog.close();$("shareButton").onclick=share;$("downloadButton").onclick=download;$("metricsButton").onclick=()=>{metrics();metricsDialog.showModal()};$("closeMetrics").onclick=()=>metricsDialog.close();$("exportButton").onclick=csv;$("resetMetricsButton").onclick=()=>{if(confirm("이 기기의 PoC 데이터를 초기화할까요?")){stats=fresh();save("reset");metrics()}};window.onresize=resize;window.onbeforeunload=()=>stream?.getTracks().forEach(t=>t.stop());select("heart",false);
